Multiple areas
instantink/image_compare pull request #6
Opened 2024-02-06 21:51 UTC by cristianofmc

Code update for better discrimination of points of difference, separating each point of difference with its own rectangle.
![image](https://github.com/instantink/image_compare/assets/27186405/58bb53c3-9fa6-4b6e-9f24-a73cbaed2cd4)

2024-02-08 20:08 UTC, gsguma commented on lib/image_compare/modes/base.rb
> +
Consider removing this extra line

2024-02-08 20:11 UTC, gsguma commented on lib/image_compare/modes/base.rb
> +        if @different_areas.any?
I think this validation is redundant (_the each method already ignores empty arrays by default_)

2024-02-08 20:16 UTC, gsguma commented on lib/image_compare/rectangle.rb
> +
Consider remove this "extra line"

2024-02-08 20:16 UTC, gsguma commented on lib/image_compare/rectangle.rb
> +
Consider remove this "extra line"

2024-02-08 20:18 UTC, gsguma commented on spec/base_spec.rb
> +require "image_compare/modes/base"
Consider using single quotes for non-interpolated strings

2024-02-08 20:18 UTC, gsguma commented on spec/base_spec.rb
> +  let(:image_a) { double("Image") }
Consider using single quotes for non-interpolated strings

2024-02-08 20:18 UTC, gsguma commented on spec/base_spec.rb
> +  let(:image_b) { double("Image") }
Consider using single quotes for non-interpolated strings

2024-02-08 20:19 UTC, gsguma commented on spec/integrations/color_spec.rb
> +      subject.difference_image.save("color_diff.png")
Consider using single quotes for non-interpolated strings

2024-02-08 20:19 UTC, gsguma commented on spec/integrations/color_spec.rb
>        expect(subject.difference_image).to eq(ImageCompare::Image.from_file(image_path("color_diff")))
Consider using single quotes for non-interpolated strings

2024-02-08 20:19 UTC, gsguma commented on spec/integrations/delta_spec.rb
>        expect(subject.difference_image).to eq(ImageCompare::Image.from_file(image_path("delta_diff")))
Consider using single quotes for non-interpolated strings

2024-02-08 20:19 UTC, gsguma commented on spec/integrations/grayscale_spec.rb
>        expect(subject.difference_image).to eq(ImageCompare::Image.from_file(image_path("grayscale_diff")))
Consider using single quotes for non-interpolated strings

2024-02-08 20:20 UTC, gsguma commented on spec/integrations/rgb_spec.rb
>        expect(subject.difference_image).to eq(ImageCompare::Image.from_file(image_path("rgb_diff")))
Consider using single quotes for non-interpolated strings

2024-02-08 20:20 UTC, gsguma approved these changes, later dismissed
Good job! 💯

2024-02-09 21:55 UTC, cristianofmc commented
![image](https://github.com/instantink/image_compare/assets/27186405/e4fcc230-7a2e-41fa-8503-3bfaac9a7d83)

2024-02-16 12:17 UTC, gsguma requested changes

2024-02-16 12:17 UTC, gsguma commented on lib/image_compare/modes/base.rb
> +        @exclude_rects = @exclude_rects = exclude_rects.empty? ? Set.new : Set.new(exclude_rects.map { |rect| Rectangle.new(*rect) })
Please consider changing to:
```
@exclude_rects = exclude_rects.empty? ? Set.new : Set.new(exclude_rects.map { |rect| Rectangle.new(*rect) })
```

_**Don't forget to fix the error on line 17 too**_

2024-02-16 12:17 UTC, gsguma commented on lib/image_compare/modes/base.rb
> +        total_exclude_area = @exclude_rects.nil? ? 0 : @exclude_rects.sum { |rect| rect.area }
Please consider changing to `total_exclude_area = @exclude_rects&.sum(&:area) || 0`

2024-02-16 12:17 UTC, gsguma commented on spec/base_spec.rb
> +end
Missing EOF

2024-02-16 12:18 UTC, gsguma requested changes

2024-02-16 12:18 UTC, gsguma commented on spec/base_spec.rb
> +
Please remove extra line

2024-02-16 12:21 UTC, gsguma commented
Don't forget to inspect code quality, running:
```
rake rubocop
rake rubocop-md
```

2024-03-18 16:23 UTC, gsguma submitted a review, later dismissed

2024-03-18 16:46 UTC, gsguma approved these changes

2024-03-18 16:47 UTC, merged